{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}-postgresql-secret
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
data:
  postgres-username: {{ .Values.postgresql.globalVariables.POSTGRES_USER | b64enc }}
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (include "keycloak.fullname" . | printf "%s-postgresql-secret") ) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  postgres-password: {{ (get $secretData "postgres-password") | default (randAlphaNum 16) | b64enc }}
{{- end }}
