apiVersion: v1
kind: Secret
metadata:
  name: "keycloak-secret"
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "keycloak-secret") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  # Admin username for Keycloak 22+
  admin-username: {{ $secretData["admin-username"] | default "admin" | b64enc }}
  # Admin password - use existing secret data or generate a random one when not exists
  admin-password: {{ (get $secretData "password") | default (randAlphaNum 16) | b64enc }}
