[tool.poetry]
authors = ["Aurelius Enterprise <info@aureliusenterprise.com>"]
description = "This library provides common utilities for working with Apache Kafka."
name = "aurelius-kafka"
version = "0.0.0"

[[tool.poetry.packages]]
include = "aurelius_kafka"

[tool.poetry.dependencies]
aws-msk-iam-sasl-signer-python = "^1.0.2"

[tool.poetry.dependencies.aurelius-sdk]
develop = true
path = "../../../libs/python/aurelius-sdk"

[tool.poetry.dependencies.confluent-kafka]
extras = ["avro", "schema-registry"]
version = "2.10.0"

[tool.poetry.extras]
msk = ["aws-msk-iam-sasl-signer-python"]

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "module"
asyncio_mode = "auto"
required_plugins = ["pytest-asyncio"]

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
