[project]
authors = [{ name = "Aurelius Enterprise" }]
description = "This library provides common utilities for working with Apache Kafka."
name = "aurelius-kafka"
requires-python = ">=3.14"
version = "0.0.0"

dependencies = [
    "aurelius-sdk",
    "aws-msk-iam-sasl-signer-python>=1.0.2",
    "confluent-kafka[avro,schema-registry]>=2.12.2",
]

[tool.hatch.build.targets.wheel]
packages = ["aurelius_kafka"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.uv.sources.aurelius-sdk]
workspace = true

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "module"
asyncio_mode = "auto"
required_plugins = ["pytest-asyncio"]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]
