sonar.host.url=https://sonarcloud.io
sonar.organization=aureliusenterprise
sonar.projectKey=m4i-update-gov-data-quality
sonar.python.version=3.8
sonar.sarifReportPaths=backend/m4i-update-gov-data-quality/vulnerabilities.sarif
sonar.sources=backend/m4i-update-gov-data-quality/m4i_update_gov_data_quality,backend/m4i-update-gov-data-quality/Dockerfile
