sonar.host.url=https://sonarcloud.io
sonar.organization=aureliusenterprise
sonar.projectKey=m4i-validate-entity
sonar.python.version=3.8
sonar.sarifReportPaths=backend/m4i-validate-entity/vulnerabilities.sarif
sonar.sources=backend/m4i-validate-entity/m4i_validate_entity,backend/m4i-validate-entity/Dockerfile
