creation_rules:
    - age: >-
          age1mmg85phratgkv7fc9w22qafuwyq2h8rfpmrqn47jcvnn57dp79gsv038km,
          age19j34kscpqkt0c5f02qv597ht3vh6fqa7aysr70yq9v0rh2e8rymsgj057h,
          age1uttv8shzffrlnld96zeq7pqlpmahv3q7w9f3jndm0an20t355ssqydyy8s,
          age126hsd662698yhqhtu2autpneeyfjrkkefr0q0dzjyxfg8ezhn9ks69tdte
