creation_rules:
    - age: >-
          age1lm45al7sy7lmevrhf9fs48kc7am4r4s5dpwh3g2aqlj8rk572cjsh27hjh,
          age1jug4lrqtgyzpuvsl4fyqgtse7es9n8hu4p6p7er3kc9akancfpxqys74rk,
          age1ef9prtdusm2794s9gzwmqamhyhzg54x53xsrq43u4htvh56tuu0q035zj8,
          age18kqejjekgyqqf8arngjxxlzzp5vhf3tv374ft6tyzg596een6u8q8w27df,
          age1vcd6mgnsetu63a34v6k5rhltkauyy6weh883dj8rsvz04sqxk9kq4756ax,
          age14he6m9kcnx3r5c5p3hmjn3zrj26w4gjfm6qgr8dxv2fnf9pd8elsl2ku9s
