[tool.poetry]
name = "aurelius-project-template"
package-mode = false
version = "0.0.0"

[tool.poetry.dependencies]
python = "^3.13"

[tool.poetry.group.dev.dependencies]
alembic = "^1.16.4"
mike = "^2.1.3"
mkdocs = "^1.6.1"
mkdocs-material = "^9.6.15"
mkdocs-print-site-plugin = "^2.7.3"
mkdocstrings = "^0.29.1"
mkdocstrings-python = "^1.16.12"
pre-commit = "^4.2.0"
pydantic = "^2.11.7"
pydantic-settings = "^2.10.1"
pymdown-extensions = "^10.16"
pyright = "^1.1.403"
pytest = "^8.4.1"
pytest-asyncio = "^1.0.0"
pytest-cov = "^6.2.1"
pytest-mock = "^3.14.1"
pytest-sugar = "^1.0.0"
python-dotenv = "^1.1.1"
ruff = "^0.12.3"
sqlalchemy = "^2.0.41"
testcontainers = "^4.10.0"

[tool.poetry.group.dev.dependencies.aurelius-fastapi-example]
develop = true
path = "apps/aurelius-fastapi-example"

[tool.poetry.group.dev.dependencies.aurelius-sdk]
develop = true
path = "libs/aurelius-sdk"

[tool.poetry.group.dev.dependencies.aurelius-testing]
develop = true
path = "libs/aurelius-testing"

[tool.pyright]
exclude = [".venv"]
pythonVersion = "3.13"
reportUnnecessaryTypeIgnoreComment = "error"
typeCheckingMode = "standard"
venvPath = "."

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "module"
asyncio_mode = "auto"
log_format = "%(message)s"
log_level = "INFO"
required_plugins = ["pytest-asyncio"]

[tool.ruff]
line-length = 120
target-version = "py313"

[tool.ruff.lint]
ignore = ["D100", "D104", "D105", "D212", "D107", "LOG015", "S311", "FIX002", "PT001"]
select = ["ALL"]

[tool.ruff.lint.flake8-type-checking]
runtime-evaluated-base-classes = ["pydantic.BaseModel", "sqlalchemy.orm.DeclarativeBase"]
runtime-evaluated-decorators = ["pydantic.validate_call", "attrs.define"]

[tool.ruff.lint.per-file-ignores]
"**/conftest.py" = ["INP001"]
"**/test__*.py" = ["INP001", "S101", "PLR2004"]

[tool.ruff.lint.pydocstyle]
convention = "google"
