name: m4i-search-api-e2e

services:
    m4i-search-api:
        configs:
            - source: certs
              target: /usr/share/elasticsearch/config/certs
        environment:
            APP_SEARCH_BASE_URL: https://enterprisesearch:${ENTERPRISE_SEARCH_PORT}
            APP_SEARCH_PASSWORD: ${APP_SEARCH_PASSWORD}
            APP_SEARCH_USERNAME: ${APP_SEARCH_USERNAME}
            APP_SEARCH_CA_CERT_PATH: /usr/share/elasticsearch/config/certs/ca/ca.crt
            AUTH_ISSUER: http://keycloak.localhost:${KEYCLOAK_HTTP_PORT}/realms/${KEYCLOAK_REALM_NAME}
            WSGI_PORT: ${WSGI_PORT}
        extra_hosts:
            - keycloak.localhost:host-gateway
        image: ghcr.io/aureliusenterprise/m4i-search-api:local
        networks:
            - aurelius-atlas-dev-network
        ports:
            - ${WSGI_PORT}
        restart: unless-stopped

configs:
    certs:
        file: ../../../dev/certs

networks:
    aurelius-atlas-dev-network:
        external: true
