---
elastic_search:
  name: elastic-search
  replicaCount: 1
  version: 9.5.4
  persistence:
    enabled: true
    # storageClass: "-"
    accessMode: ReadWriteOnce
    size: 8Gi
  resources:
    requests: { cpu: 500m, memory: 2Gi }
    limits: { memory: 2Gi }

kibana:
  name: kibana
  replicaCount: 1
  version: 9.5.4
