name: aurelius-java-producer-example-e2e

services:
    aurelius-java-producer-example:
        environment:
            KAFKA_BOOTSTRAP_SERVERS: broker:9094
            KAFKA_TOPIC_NAME: ${KAFKA_TOPIC_NAME}
            SCHEMA_REGISTRY_URL: http://schema-registry:8081
        image: ghcr.io/aureliusenterprise/aurelius-java-producer-example:local
        restart: unless-stopped
        networks:
            - aurelius-dev-kafka-network
            - default
        ports:
            - 1880

networks:
    aurelius-dev-kafka-network:
        external: true
