#!/bin/sh
# Writes .env with random secrets next to docker-compose.yml (Linux/macOS; start.bat does the same on Windows).
# Existing values are kept; secrets missing in an existing .env (added by a newer version of the stack) are appended.
cd "$(dirname "$0")"
rnd() { head -c 48 /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | head -c "$1"; }
umask 077
[ -f .env ] || echo "# generated by init-env.sh - keep this file private (it is in .gitignore)" > .env
added=""
for spec in KEYCLOAK_ADMIN_PASSWORD:24 PYATLAS_SESSION_SECRET:40 AURELIUS_PROXY_CRYPTO_PASSPHRASE:40 \
            ELASTIC_PASSWORD:24 KIBANA_SYSTEM_PASSWORD:24 KIBANA_ENCRYPTION_KEY:40 PYATLAS_ES_PASSWORD:24 \
            FILEBEAT_PASSWORD:24 AURELIUS_OPERATOR_PASSWORD:16; do
  name=${spec%%:*}; len=${spec#*:}
  grep -q "^$name=" .env || { echo "$name=$(rnd "$len")" >> .env; added="$added $name"; }
done
[ -n "$added" ] && echo ".env: added$added" || echo ".env complete - nothing to do"
