# Writes .env with random secrets next to docker-compose.yml (Windows; called by start.bat).
# Existing values are kept: the file is only created when it does not exist yet.
$env_file = Join-Path $PSScriptRoot '.env'
if (Test-Path $env_file) { Write-Host '.env exists - nothing to do'; exit 0 }
function New-Secret([int]$n) {
    $chars = [char[]]'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'
    $bytes = New-Object byte[] $n
    [Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    -join ($bytes | ForEach-Object { $chars[$_ % $chars.Length] })
}
$lines = @(
    '# generated by init-env.ps1 - keep this file private (it is in .gitignore)',
    ('KEYCLOAK_ADMIN_PASSWORD=' + (New-Secret 24)),
    ('PYATLAS_SESSION_SECRET=' + (New-Secret 40)),
    ('AURELIUS_PROXY_CLIENT_SECRET=' + (New-Secret 32)),
    ('AURELIUS_PROXY_CRYPTO_PASSPHRASE=' + (New-Secret 40))
)
[IO.File]::WriteAllLines($env_file, $lines)
Write-Host "Secrets written to $env_file"
