#!/bin/sh
# Writes .env with random secrets next to docker-compose.yml (Linux/macOS; start.bat does the same on Windows).
# Existing values are kept: the file is only created when it does not exist yet.
cd "$(dirname "$0")"
[ -f .env ] && { echo ".env exists - nothing to do"; exit 0; }
rnd() { head -c 32 /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | head -c "$1"; }
umask 077
cat > .env <<ENV
# generated by init-env.sh - keep this file private (it is in .gitignore)
KEYCLOAK_ADMIN_PASSWORD=$(rnd 24)
PYATLAS_SESSION_SECRET=$(rnd 40)
AURELIUS_PROXY_CLIENT_SECRET=$(rnd 32)
AURELIUS_PROXY_CRYPTO_PASSPHRASE=$(rnd 40)
ENV
echo ".env written (Keycloak admin password: see KEYCLOAK_ADMIN_PASSWORD in .env)"
