# Writes .env with random secrets next to docker-compose.yml (Windows; called by start.bat).
# Existing values are kept; secrets missing in an existing .env (added by a newer version of the stack) are appended.
$env_file = Join-Path $PSScriptRoot '.env'
function New-Secret([int]$n) {
    $chars = [char[]]'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'
    $bytes = New-Object byte[] $n
    [Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    -join ($bytes | ForEach-Object { $chars[$_ % $chars.Length] })
}
$wanted = [ordered]@{
    'KEYCLOAK_ADMIN_PASSWORD' = 24; 'PYATLAS_SESSION_SECRET' = 40; 'AURELIUS_PROXY_CRYPTO_PASSPHRASE' = 40;
    'ELASTIC_PASSWORD' = 24; 'KIBANA_SYSTEM_PASSWORD' = 24; 'KIBANA_ENCRYPTION_KEY' = 40; 'PYATLAS_ES_PASSWORD' = 24;
    'FILEBEAT_PASSWORD' = 24; 'AURELIUS_OPERATOR_PASSWORD' = 16
}
$lines = @()
if (Test-Path $env_file) { $lines = @(Get-Content $env_file) }
else { $lines = @('# generated by init-env.ps1 - keep this file private (it is in .gitignore)') }
$added = @()
foreach ($name in $wanted.Keys) {
    if (-not ($lines | Where-Object { $_ -like "$name=*" })) {
        $lines += ($name + '=' + (New-Secret $wanted[$name])); $added += $name
    }
}
[IO.File]::WriteAllLines($env_file, [string[]]$lines)
if ($added.Count -gt 0) { Write-Host ('.env: added ' + ($added -join ', ')) } else { Write-Host '.env complete - nothing to do' }
