sonar.host.url=https://sonarcloud.io
sonar.organization=aureliusenterprise
sonar.projectKey=aurelius-node-red-example
sonar.sources=Dockerfile,flows.json,settings.js,settings.prod.js
sonar.tests=e2e
sonar.python.version=3.14
