sonar.host.url=https://sonarcloud.io
sonar.organization=aureliusenterprise
sonar.projectKey=aurelius-node-red-example
sonar.sources=apps/aurelius-node-red-example/Dockerfile,apps/aurelius-node-red-example/flows.json,apps/aurelius-node-red-example/settings.js,apps/aurelius-node-red-example/settings.prod.js
sonar.tests=apps/aurelius-node-red-example/e2e
sonar.python.version=3.14
