[project]
dependencies = [
    "aurelius-example",
    "aurelius-sdk",
    "fastapi>=0.116.1",
    "httpx>=0.28.1",
    "psycopg2>=2.9.10",
    "pydantic>=2.11.7",
    "pydantic-settings>=2.10.1",
    "pyjwt>=2.10.1",
    "uvicorn[standard]>=0.35.0",
]
description = "This is an example FastAPI application."
name = "aurelius-fastapi-example"
requires-python = ">=3.14"
version = "0.1.0"

[[project.authors]]
name = "Aurelius Enterprise"

[tool.hatch.build.targets.wheel]
packages = ["aurelius_fastapi_example"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "module"
asyncio_mode = "auto"
required_plugins = ["pytest-asyncio"]

[tool.uv.sources.aurelius-example]
workspace = true

[tool.uv.sources.aurelius-sdk]
workspace = true

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]
