sonar.host.url=https://sonarcloud.io
sonar.organization=aureliusenterprise
sonar.projectKey=aurelius-fastapi-example
sonar.python.coverage.reportPaths=apps/aurelius-fastapi-example/coverage.xml
sonar.python.version=3.14
sonar.sarifReportPaths=apps/aurelius-fastapi-example/vulnerabilities.sarif
sonar.sources=apps/aurelius-fastapi-example/aurelius_fastapi_example,apps/aurelius-fastapi-example/Dockerfile
sonar.tests=apps/aurelius-fastapi-example/tests,apps/aurelius-fastapi-example/e2e
