name=aurelius-kafka-connect-jdbc-sink-example
connector.class=io.debezium.connector.jdbc.JdbcSinkConnector
tasks.max=1

batch.size=200
consumer.override.auto.offset.reset=earliest
consumer.override.group.id=${env:CONSUMER_GROUP_NAME}
connection.password=${env:DATABASE_PASSWORD}
connection.url=${env:DATABASE_URL}
connection.username=${env:DATABASE_USERNAME}
delete.enabled=true
errors.deadletterqueue.context.headers.enable=true
errors.deadletterqueue.topic.name=${env:DLQ_TOPIC_NAME}
errors.deadletterqueue.topic.replication.factor=1
insert.mode=upsert
primary.key.fields=guid
primary.key.mode=record_key
schema.evolution=none
table.name.format=${env:TABLE_NAME}
topics=${env:KAFKA_TOPIC_NAME}
transforms=hoist-primary-key,flatten
transforms.flatten.delimiter=.
transforms.flatten.type=org.apache.kafka.connect.transforms.Flatten$Value
transforms.hoist-primary-key.field=guid
transforms.hoist-primary-key.type=org.apache.kafka.connect.transforms.HoistField$Key
