batch.size=200
bootstrap.servers=${env:KAFKA_BOOTSTRAP_SERVERS}
config.providers=env
config.providers.env.class=org.apache.kafka.common.config.provider.EnvVarConfigProvider
connector.client.config.override.policy=All
config.storage.cleanup.policy=compact
config.storage.replication.factor=1
config.storage.topic=${env:CONFIG_STORAGE_TOPIC}
group.id=${env:GROUP_ID}
key.converter=org.apache.kafka.connect.storage.StringConverter
key.converter.schemas.enable=false
log4j.root.loglevel=INFO
offset.storage.cleanup.policy=compact
offset.storage.file.filename=/tmp/connect-standalone.offsets
offset.storage.replication.factor=1
offset.storage.topic=${env:OFFSET_STORAGE_TOPIC}
plugin.path=/usr/share/confluent-hub-components
rest.advertised.host.name=${env:REST_ADVERTISED_HOST_NAME}
rest.port=${env:REST_PORT}
status.storage.cleanup.policy=compact
status.storage.replication.factor=1
status.storage.topic=${env:STATUS_STORAGE_TOPIC}
value.converter=io.confluent.connect.avro.AvroConverter
value.converter.schema.registry.url=${env:SCHEMA_REGISTRY_URL}
value.converter.schemas.enable=true
value.converter.value.subject.name.strategy=io.confluent.kafka.serializers.subject.RecordNameStrategy
