name: aurelius-kafka-connect-jdbc-sink-example

services:
    kafka-connect:
        image: ghcr.io/aureliusenterprise/aurelius-kafka-connect-jdbc-sink-example:local
        environment:
            CONFIG_CONSUMER_GROUP_NAME: ${CONNECT_CONSUMER_GROUP_NAME}
            CONFIG_DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
            CONFIG_DATABASE_URL: jdbc:postgresql://postgres:5432/aurelius
            CONFIG_DATABASE_USERNAME: ${POSTGRES_USER}
            CONFIG_DLQ_TOPIC_NAME: ${CONNECT_DLQ_TOPIC_NAME}
            CONFIG_KAFKA_TOPIC_NAME: ${CONNECT_TOPIC_NAME}
            CONFIG_SCHEMA_REGISTRY_URL: http://schema-registry:8081
            CONFIG_TABLE_NAME: ${CONNECT_TABLE_NAME}
            CONNECT_BOOTSTRAP_SERVERS: broker:9094
            CONNECT_CONFIG_PROVIDERS: file
            CONNECT_CONFIG_PROVIDERS_FILE_CLASS: org.apache.kafka.common.config.provider.FileConfigProvider
            CONNECT_CONFIG_STORAGE_CLEANUP_POLICY: compact
            CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
            CONNECT_CONFIG_STORAGE_TOPIC: aurelius-kafka-connect-jdbc-sink-example.connect-configs
            CONNECT_GROUP_ID: aurelius-kafka-connect-jdbc-sink-example.connect-group
            CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
            CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: false
            CONNECT_LOG4J_ROOT_LOGLEVEL: INFO
            CONNECT_OFFSET_STORAGE_CLEANUP_POLICY: compact
            CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
            CONNECT_OFFSET_STORAGE_TOPIC: aurelius-kafka-connect-jdbc-sink-example.connect-offsets
            CONNECT_REST_ADVERTISED_HOST_NAME: localhost
            CONNECT_REST_PORT: 8083
            CONNECT_STATUS_STORAGE_CLEANUP_POLICY: compact
            CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
            CONNECT_STATUS_STORAGE_TOPIC: aurelius-kafka-connect-jdbc-sink-example.connect-status
            CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
            CONNECT_VALUE_CONVERTER_VALUE_SUBJECT_NAME_STRATEGY: io.confluent.kafka.serializers.subject.RecordNameStrategy
            CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: true
            CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
        networks:
            - aurelius-dev-kafka-network
            - aurelius-dev-postgres-network

networks:
    aurelius-dev-kafka-network:
        external: true

    aurelius-dev-postgres-network:
        external: true
