name: aurelius-kafka-connect-jdbc-sink-example

services:
    kafka-connect:
        image: ghcr.io/aureliusenterprise/aurelius-kafka-connect-jdbc-sink-example:local
        entrypoint: ["/opt/kafka/bin/connect-standalone.sh"]
        command: ["/connect-worker", "/connect-connector"]
        configs:
            - connect-worker
            - connect-connector
        environment:
            CONSUMER_GROUP_NAME: ${CONSUMER_GROUP_NAME}
            DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
            DATABASE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
            DATABASE_USERNAME: ${POSTGRES_USER}
            DLQ_TOPIC_NAME: ${DLQ_TOPIC_NAME}
            KAFKA_TOPIC_NAME: ${KAFKA_TOPIC_NAME}
            SCHEMA_REGISTRY_URL: http://schema-registry:8081
            TABLE_NAME: ${TABLE_NAME}
            KAFKA_BOOTSTRAP_SERVERS: broker:9094
            CONFIG_STORAGE_TOPIC: aurelius-kafka-connect-jdbc-sink-example.connect-configs
            GROUP_ID: aurelius-kafka-connect-jdbc-sink-example.connect-group
            OFFSET_STORAGE_TOPIC: aurelius-kafka-connect-jdbc-sink-example.connect-offsets
            REST_ADVERTISED_HOST_NAME: localhost
            REST_PORT: 8083
            STATUS_STORAGE_TOPIC: aurelius-kafka-connect-jdbc-sink-example.connect-status
        networks:
            - aurelius-dev-kafka-network
            - aurelius-dev-postgres-network

configs:
    connect-worker:
        file: ./workers/worker.properties
    connect-connector:
        file: ./workers/connector.properties

networks:
    aurelius-dev-kafka-network:
        external: true

    aurelius-dev-postgres-network:
        external: true
