[project]
dependencies = ["pydantic>=2.11.7", "pydantic-avro>=0.9.0", "sqlmodel>=0.0.24"]
description = "This library provides common utilities for example projects."
name = "aurelius-example"
requires-python = ">=3.14"
version = "0.2.0"

[[project.authors]]
name = "Aurelius Enterprise"

[tool.hatch.build.targets.wheel]
packages = ["aurelius_example"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "module"
asyncio_mode = "auto"
required_plugins = ["pytest-asyncio"]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]
