"""The three Aurelius search engines (formerly Elastic App Search), as defined in
``backend/m4i-atlas-post-install/m4i_atlas_post_install/app_search_engine_setup.py``: field types, search
fields with their weights and the default result fields.  pyatlas keeps one Elasticsearch index per engine
(``<prefix>_aurelius_<engine>``) and answers App Search queries on them (:mod:`pyatlas.aurelius.appsearch`)."""

ENGINES = {'atlas-dev': {'result_fields': {'definition': {'raw': {}, 'snippet': {'fallback': True, 'size': 200}},
                                 'derivedcollection': {'raw': {}},
                                 'deriveddataattribute': {'raw': {}},
                                 'deriveddatadomain': {'raw': {}},
                                 'deriveddataentity': {'raw': {}},
                                 'deriveddataset': {'raw': {}},
                                 'derivedfield': {'raw': {}},
                                 'derivedperson': {'raw': {}},
                                 'derivedprocess': {'raw': {}},
                                 'derivedsystem': {'raw': {}},
                                 'guid': {'raw': {}},
                                 'name': {'raw': {}, 'snippet': {'fallback': True, 'size': 150}},
                                 'supertypenames': {'raw': {}},
                                 'typealias': {'raw': {}},
                                 'typename': {'raw': {}}},
               'schema': {'breadcrumbguid': 'text',
                          'breadcrumbname': 'text',
                          'breadcrumbtype': 'text',
                          'businessruleid': 'number',
                          'classificationstext': 'text',
                          'definition': 'text',
                          'derivedcollection': 'text',
                          'derivedcollectionguid': 'text',
                          'deriveddataattribute': 'text',
                          'deriveddataattributeguid': 'text',
                          'deriveddatadomain': 'text',
                          'deriveddatadomainguid': 'text',
                          'deriveddataentity': 'text',
                          'deriveddataentityguid': 'text',
                          'deriveddataownerguid': 'text',
                          'deriveddataset': 'text',
                          'deriveddatasetguid': 'text',
                          'deriveddatasetguids': 'text',
                          'deriveddatasetnames': 'text',
                          'deriveddatastewardguid': 'text',
                          'deriveddomainleadguid': 'text',
                          'derivedentityguids': 'text',
                          'derivedentitynames': 'text',
                          'derivedfield': 'text',
                          'derivedfieldguid': 'text',
                          'derivedperson': 'text',
                          'derivedpersonguid': 'text',
                          'derivedprocess': 'text',
                          'derivedprocessguid': 'text',
                          'derivedsystem': 'text',
                          'derivedsystemguid': 'text',
                          'dqscore_accuracy': 'number',
                          'dqscore_completeness': 'number',
                          'dqscore_overall': 'number',
                          'dqscore_timeliness': 'number',
                          'dqscore_uniqueness': 'number',
                          'dqscore_validity': 'number',
                          'dqscorecnt_accuracy': 'number',
                          'dqscorecnt_completeness': 'number',
                          'dqscorecnt_overall': 'number',
                          'dqscorecnt_timeliness': 'number',
                          'dqscorecnt_uniqueness': 'number',
                          'dqscorecnt_validity': 'number',
                          'dqscoresum_accuracy': 'number',
                          'dqscoresum_completeness': 'number',
                          'dqscoresum_overall': 'number',
                          'dqscoresum_timeliness': 'number',
                          'dqscoresum_uniqueness': 'number',
                          'dqscoresum_validity': 'number',
                          'email': 'text',
                          'entityname': 'text',
                          'guid': 'text',
                          'm4isourcetype': 'text',
                          'name': 'text',
                          'parentguid': 'text',
                          'qualityguid_accuracy': 'text',
                          'qualityguid_completeness': 'text',
                          'qualityguid_timeliness': 'text',
                          'qualityguid_uniqueness': 'text',
                          'qualityguid_validity': 'text',
                          'referenceablequalifiedname': 'text',
                          'sourcetype': 'text',
                          'supertypenames': 'text',
                          'typealias': 'text',
                          'typename': 'text'},
               'search_fields': {'definition': 1,
                                 'derivedcollection': 1,
                                 'deriveddataattribute': 1,
                                 'deriveddatadomain': 1,
                                 'deriveddataentity': 1,
                                 'deriveddataset': 1,
                                 'derivedfield': 1,
                                 'derivedperson': 1,
                                 'derivedprocess': 1,
                                 'derivedsystem': 1,
                                 'email': 1,
                                 'guid': 1,
                                 'id': 1,
                                 'name': 3,
                                 'typealias': 1,
                                 'typename': 1}},
 'atlas-dev-gov-quality': {'result_fields': {'business_rule_id': {'raw': {}},
                                             'compliant': {'raw': {}},
                                             'dataqualityruledescription': {'raw': {}},
                                             'dataqualityruledimension': {'raw': {}},
                                             'dataqualityruletypename': {'raw': {}},
                                             'dataqualitytype': {'raw': {}},
                                             'doc_guid': {'raw': {}},
                                             'entity_guid': {'raw': {}},
                                             'expression': {'raw': {}},
                                             'guid': {'raw': {}},
                                             'id': {'raw': {}},
                                             'name': {'raw': {}},
                                             'noncompliant_message': {'raw': {}},
                                             'qualifiedname': {'raw': {}},
                                             'qualityqualifiedname': {'raw': {}},
                                             'result': {'raw': {}},
                                             'result_id': {'raw': {}},
                                             'usedattributes': {'raw': {}}},
                           'schema': {'business_rule_id': 'text',
                                      'compliant': 'text',
                                      'dataqualityruledescription': 'text',
                                      'dataqualityruledimension': 'text',
                                      'dataqualityruletypename': 'text',
                                      'dataqualitytype': 'text',
                                      'doc_guid': 'text',
                                      'entity_guid': 'text',
                                      'expression': 'text',
                                      'guid': 'text',
                                      'name': 'text',
                                      'noncompliant_message': 'text',
                                      'qualifiedname': 'text',
                                      'qualityqualifiedname': 'text',
                                      'result': 'text',
                                      'result_id': 'text',
                                      'usedattributes': 'text'},
                           'search_fields': {'business_rule_id': 1,
                                             'compliant': 1,
                                             'dataqualityruledescription': 1,
                                             'dataqualityruledimension': 1,
                                             'dataqualityruletypename': 1,
                                             'dataqualitytype': 1,
                                             'doc_guid': 1,
                                             'entity_guid': 1,
                                             'expression': 1,
                                             'guid': 1,
                                             'id': 1,
                                             'name': 1,
                                             'noncompliant_message': 1,
                                             'qualifiedname': 1,
                                             'qualityqualifiedname': 1,
                                             'result': 1,
                                             'result_id': 1,
                                             'usedattributes': 1}},
 'atlas-dev-quality': {'result_fields': {'businessruleid': {'raw': {}},
                                         'datadomainname': {'raw': {}},
                                         'dataqualityruledescription': {'raw': {}},
                                         'dataqualityruledimension': {'raw': {}},
                                         'dqscore': {'raw': {}},
                                         'expression': {'raw': {}},
                                         'fieldguid': {'raw': {}},
                                         'fieldqualifiedname': {'raw': {}},
                                         'guid': {'raw': {}},
                                         'id': {'raw': {}},
                                         'name': {'raw': {}},
                                         'qualifiedname': {'raw': {}},
                                         'qualityguid': {'raw': {}},
                                         'qualityqualifiedname': {'raw': {}}},
                       'schema': {'businessruleid': 'number',
                                  'datadomainname': 'text',
                                  'dataqualityruledescription': 'text',
                                  'dataqualityruledimension': 'text',
                                  'dqscore': 'number',
                                  'expression': 'text',
                                  'fieldguid': 'text',
                                  'fieldqualifiedname': 'text',
                                  'guid': 'text',
                                  'name': 'text',
                                  'qualifiedname': 'text',
                                  'qualityguid': 'text',
                                  'qualityqualifiedname': 'text'},
                       'search_fields': {'datadomainname': 1,
                                         'dataqualityruledescription': 3.1,
                                         'dataqualityruledimension': 1,
                                         'expression': 1,
                                         'fieldqualifiedname': 1,
                                         'id': 1,
                                         'qualifiedname': 1,
                                         'qualityqualifiedname': 1}}}

# the old names of the engines, as the frontend's proxy routes and the golden files use them
SEARCH_DOCUMENTS = "atlas-dev"
DATA_QUALITY = "atlas-dev-quality"
GOV_QUALITY = "atlas-dev-gov-quality"


def index_suffix(engine: str) -> str:
    return "aurelius_" + engine.replace("-", "_")


def mapping(engine: str) -> dict:
    """keyword field (filters, facets, sorting) with an analysed ``.text`` sub-field (full-text search)."""
    props = {"id": {"type": "keyword"}}
    for name, kind in ENGINES[engine]["schema"].items():
        if kind == "number":
            props[name] = {"type": "double"}
        elif kind == "date":
            props[name] = {"type": "date"}
        else:
            props[name] = {"type": "keyword", "ignore_above": 8191,
                           "fields": {"text": {"type": "text", "analyzer": "atlas_text"}}}
    return {"dynamic": True, "properties": props}
