sonar.host.url=https://sonarcloud.io
sonar.organization=aureliusenterprise
sonar.projectKey=aurelius-atlas-test-report
sonar.python.coverage.reportPaths=reports/aurelius-atlas-test-report/coverage.xml
sonar.python.version=3.14
sonar.sources=reports/aurelius-atlas-test-report/aurelius_atlas_test_report
sonar.tests=reports/aurelius-atlas-test-report/tests
