[project]
dependencies = [
    "aurelius-aws-lambda",
    "aurelius-example",
    "aurelius-kafka",
    "aws-lambda-powertools>=3.17.0",
    "confluent-kafka[avro,schema-registry]>=2.13.2",
    "pydantic>=2.11.7",
    "pydantic-settings>=2.10.1",
]
description = "This is an example AWS lambda function."
name = "aurelius-aws-lambda-example"
requires-python = ">=3.14"
version = "0.2.0"

[[project.authors]]
name = "Aurelius Enterprise "

[tool.hatch.build.targets.wheel]
packages = ["aurelius_aws_lambda_example"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "module"
asyncio_mode = "auto"
required_plugins = ["pytest-asyncio"]

[tool.uv.sources.aurelius-aws-lambda]
workspace = true

[tool.uv.sources.aurelius-example]
workspace = true

[tool.uv.sources.aurelius-kafka]
workspace = true

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]
