sonar.host.url=https://sonarcloud.io
sonar.organization=aureliusenterprise
sonar.projectKey=aurelius-aws-lambda-example
sonar.python.coverage.reportPaths=apps/aurelius-aws-lambda-example/coverage.xml
sonar.python.version=3.14
sonar.sources=apps/aurelius-aws-lambda-example/aurelius_aws_lambda_example,apps/aurelius-aws-lambda-example/Dockerfile
sonar.tests=apps/aurelius-aws-lambda-example/tests,apps/aurelius-aws-lambda-example/e2e
