name: aurelius-node-red-example-e2e

services:
    aurelius-node-red-example:
        environment:
            KAFKA_BOOTSTRAP_SERVERS: broker:9094
            KAFKA_TOPIC_NAME: ${KAFKA_TOPIC_NAME}
            SCHEMA_REGISTRY_URL: http://schema-registry:8081
            SCHEMA_SUBJECT_NAME: ${SCHEMA_SUBJECT_NAME}
            SCHEMA_SUBJECT_VERSION: ${SCHEMA_SUBJECT_VERSION}
        image: ghcr.io/aureliusenterprise/aurelius-node-red-example:local
        networks:
            - aurelius-dev-kafka-network
            - default
        ports:
            - 1880
        restart: unless-stopped

networks:
    aurelius-dev-kafka-network:
        external: true
