sonar.host.url=https://sonarcloud.io
sonar.organization=aureliusenterprise
sonar.projectKey=m4i-lineage-rest-api
sonar.python.version=3.8
sonar.sarifReportPaths=backend/m4i-lineage-rest-api/vulnerabilities.sarif
sonar.sources=backend/m4i-lineage-rest-api/m4i_lineage_rest_api,backend/m4i-lineage-rest-api/Dockerfile
sonar.source.exclusions=**/test_*.py
sonar.tests=backend/m4i-lineage-rest-api/m4i_lineage_rest_api,backend/m4i-lineage-rest-api/tests
sonar.test.inclusions=**/test_*.py
