[tool.poetry]
authors = ["Aurelius Enterprise <info@aureliusenterprise.com>"]
description = "App for importing data dictionaries into Aurelius Atlas"
license = 'UNLICENSED'
name = "m4i-data-dictionary-io"
readme = 'README.md'
version = "1.0.0"

[[tool.poetry.packages]]
include = "m4i_data_dictionary_io"

[tool.poetry.dependencies]
apache-flink = "^2.0"
avro-python3 = ">=1.10,<1.11"
confluent-kafka = ">=2.6,<3"
dataclasses-json = ">=0.6,<1"
openpyxl = "^3.1.5"
pandas = "^2.2"
python = ">=3.10,<3.14"
tenacity = ">=8.5.0"
urllib3 = ">=1.26.18"

[tool.poetry.dependencies.m4i-atlas-core]
develop = true
path = "../../libs/m4i-atlas-core"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
