sonar.host.url=https://sonarcloud.io
sonar.organization=aureliusenterprise
sonar.projectKey=m4i-data-dictionary-io
sonar.python.coverage.reportPaths=apps/m4i-data-dictionary-io/coverage.xml
sonar.python.version=3.8
sonar.sarifReportPaths=apps/m4i-data-dictionary-io/vulnerabilities.sarif
sonar.sources=apps/m4i-data-dictionary-io/m4i_data_dictionary_io,apps/m4i-data-dictionary-io/Dockerfile
sonar.tests=apps/m4i-data-dictionary-io/tests
