[tool.poetry]
name = "aurelius-kafka-connect-jdbc-sink"
package-mode = false
version = "0.0.0"

[tool.poetry.dependencies.aurelius-kafka-connect]
develop = true
path = "../../docker/aurelius-kafka-connect"

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "module"
asyncio_mode = "auto"
log_format = "%(message)s"
log_level = "INFO"
required_plugins = ["pytest-asyncio"]
