sonar.host.url=https://sonarcloud.io
sonar.organization=aureliusenterprise
sonar.projectKey=aurelius-java-producer-example
sonar.sarifReportPaths=apps/aurelius-java-producer-example/vulnerabilities.sarif
sonar.sources=apps/aurelius-java-producer-example/src/main/java,apps/aurelius-java-producer-example/Dockerfile
sonar.tests=apps/aurelius-java-producer-example/e2e,apps/aurelius-java-producer-example/src/test/java
sonar.java.binaries=apps/aurelius-java-producer-example/build/classes/java/main
sonar.java.test.binaries=apps/aurelius-java-producer-example/build/classes/java/test
sonar.coverage.jacoco.xmlReportPaths=apps/aurelius-java-producer-example/build/reports/jacoco/test/jacocoTestReport.xml
