sonar.host.url=https://sonarcloud.io
sonar.organization=aureliusenterprise
sonar.projectKey=aurelius-java-producer-example
sonar.sources=src/main/java,Dockerfile
sonar.tests=e2e,src/test/java
sonar.java.binaries=build/classes
