sonar.host.url=https://sonarcloud.io
sonar.organization=aureliusenterprise
sonar.projectKey=m4i-consistency-metrics
sonar.sources=apps/consistency-metrics/src
sonar.source.exclusions=**/*.spec.ts
sonar.tests=apps/consistency-metrics/src
sonar.test.inclusions=**/*.spec.ts
