[tool.poetry]
authors = ["Aurelius Enterprise <info@aureliusenterprise.com>"]
description = "Functions for calculating model consistency metrics"
license = 'UNLICENSED'
name = "m4i-metrics"
readme = 'README.md'
version = "1.0.0"

[[tool.poetry.packages]]
include = "m4i_metrics"

[tool.poetry.dependencies]
bokeh = "^3.1"
networkx = "^3.0"
numpy = "^1.26"
pandas = "^2.0"
python = ">=3.10,<3.14"

[tool.poetry.dependencies.m4i-analytics]
develop = true
path = "../m4i-analytics"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
