sonar.host.url=https://sonarcloud.io
sonar.organization=aureliusenterprise
sonar.projectKey=m4i-platform
sonar.sarifReportPaths=apps/platform/vulnerabilities.sarif
sonar.sources=apps/platform/src
sonar.source.exclusions=**/*.spec.ts
sonar.tests=apps/platform/src
sonar.test.inclusions=**/*.spec.ts
