name: aurelius-fastapi-example-e2e

services:
    aurelius-fastapi-example:
        image: aurelius-fastapi-example:latest
        ports:
            - 8000
        environment:
            LOG_LEVEL: ${LOG_LEVEL}
