name: aurelius-dev-kafka

services:
    broker:
        image: dhi.io/kafka:4.3-debian13
        ports:
            - "9092:9092"
            - "9094:9094"
        healthcheck:
            test: /opt/kafka/bin/kafka-topics.sh --list --bootstrap-server broker:9094 || exit 1
            interval: 15s
            timeout: 10s
            retries: 20
            start_period: 30s
        restart: unless-stopped
        volumes:
            - ./server.properties:/opt/kafka/config/server.properties
            - kafka-data:/opt/kafka/logs
            - kafka-kraft:/tmp/kraft-combined-logs

    schema-registry:
        image: confluentinc/cp-schema-registry:8.2.1
        depends_on:
            broker:
                condition: service_healthy
        environment:
            SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "PLAINTEXT://broker:9094"
            SCHEMA_REGISTRY_HOST_NAME: "schema-registry"
        restart: unless-stopped
        ports:
            - 8081:${SCHEMA_REGISTRY_PORT}
        healthcheck:
            test:
                [
                    "CMD",
                    "curl",
                    "--output",
                    "/dev/null",
                    "--silent",
                    "--head",
                    "--fail",
                    "http://schema-registry:8081/subjects",
                ]
            interval: 30s
            timeout: 10s
            retries: 10

    kafka-ui:
        image: kafbat/kafka-ui:latest
        depends_on:
            - broker
            - schema-registry
        environment:
            KAFKA_CLUSTERS_0_NAME: aurelius-dev-kafka
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:9094
            KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
            SERVER_PORT: ${KAFKA_UI_PORT}
        ports:
            - ${KAFKA_UI_PORT}:${KAFKA_UI_PORT}
        restart: unless-stopped

networks:
    default:
        name: aurelius-dev-kafka-network

volumes:
    kafka-data:
    kafka-kraft:
