sonar.host.url=https://sonarcloud.io
sonar.organization=aureliusenterprise
sonar.projectKey=m4i-lineage-model
sonar.python.version=3.8
sonar.sarifReportPaths=backend/m4i-lineage-model/vulnerabilities.sarif
sonar.sources=backend/m4i-lineage-model/m4i_lineage_model,backend/m4i-lineage-model/Dockerfile
