sonar.host.url=https://sonarcloud.io
sonar.organization=aureliusenterprise
sonar.projectKey=aurelius-atlas-server
sonar.python.coverage.reportPaths=apps/aurelius-atlas-server/coverage.xml
sonar.python.version=3.14
sonar.sources=apps/aurelius-atlas-server/aurelius_atlas_server
sonar.tests=apps/aurelius-atlas-server/tests
