sonar.host.url=https://sonarcloud.io
sonar.organization=aureliusenterprise
sonar.projectKey=aurelius-kafka-connect-base
sonar.sources=docker/aurelius-kafka-connect-base/Dockerfile,docker/aurelius-kafka-connect-base/bin
