[tool.poetry]
authors = ["Aurelius Enterprise <info@aureliusenterprise.com>"]
description = "This library provides common utilities for Aurelius projects."
name = "aurelius-sdk"
version = "0.0.0"

[[tool.poetry.packages]]
include = "aurelius_sdk"

[tool.poetry.dependencies]
coloredlogs = { version = "^15.0.1", optional = true }
httpx = { version = "^0.28.1", optional = true }
msal = { version = "^1.32.3", optional = true }

[tool.poetry.extras]
logger = ["coloredlogs"]
msal = ["httpx", "msal"]

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "module"
asyncio_mode = "auto"
required_plugins = ["pytest-asyncio"]

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
