[tool.poetry]
authors = ["Aurelius Enterprise <info@aureliusenterprise.com>"]
description = "This library provides common utilities for working with AWS lambda functions."
name = "aurelius-aws-lambda"
version = "0.0.0"

[[tool.poetry.packages]]
include = "aurelius_aws_lambda"

[tool.poetry.dependencies]
pydantic = "^2.11.7"

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "module"
asyncio_mode = "auto"
required_plugins = ["pytest-asyncio"]

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
