/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.aureliusenterprise.example;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;

@org.apache.avro.specific.AvroGenerated
public class Entity
    extends org.apache.avro.specific.SpecificRecordBase
    implements org.apache.avro.specific.SpecificRecord
{

    private static final long serialVersionUID = 1164637377708274102L;

    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse(
        "{\"type\":\"record\",\"name\":\"Entity\",\"namespace\":\"com.aureliusenterprise.example\",\"fields\":[{\"name\":\"description\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"A description of the entity\",\"default\":null},{\"name\":\"guid\",\"type\":[\"null\",{\"type\":\"string\",\"logicalType\":\"uuid\"}],\"doc\":\"The unique identifier for the entity\",\"default\":null},{\"name\":\"name\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"The name of the entity\",\"default\":null},{\"name\":\"time_created\",\"type\":[\"null\",{\"type\":\"long\",\"logicalType\":\"timestamp-micros\"}],\"doc\":\"The timestamp when the entity was created\",\"default\":null},{\"name\":\"time_modified\",\"type\":[\"null\",{\"type\":\"long\",\"logicalType\":\"timestamp-micros\"}],\"doc\":\"The timestamp when the entity was last modified\",\"default\":null}]}"
    );

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

    private static final SpecificData MODEL$ = new SpecificData();

    static {
        MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.UUIDConversion());
        MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMicrosConversion());
    }

    private static final BinaryMessageEncoder<Entity> ENCODER = new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

    private static final BinaryMessageDecoder<Entity> DECODER = new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

    /**
     * Return the BinaryMessageEncoder instance used by this class.
     * @return the message encoder used by this class
     */
    public static BinaryMessageEncoder<Entity> getEncoder() {
        return ENCODER;
    }

    /**
     * Return the BinaryMessageDecoder instance used by this class.
     * @return the message decoder used by this class
     */
    public static BinaryMessageDecoder<Entity> getDecoder() {
        return DECODER;
    }

    /**
     * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
     * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
     * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
     */
    public static BinaryMessageDecoder<Entity> createDecoder(SchemaStore resolver) {
        return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
    }

    /**
     * Serializes this Entity to a ByteBuffer.
     * @return a buffer holding the serialized data for this instance
     * @throws java.io.IOException if this instance could not be serialized
     */
    public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
        return ENCODER.encode(this);
    }

    /**
     * Deserializes a Entity from a ByteBuffer.
     * @param b a byte buffer holding serialized data for an instance of this class
     * @return a Entity instance decoded from the given buffer
     * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
     */
    public static Entity fromByteBuffer(java.nio.ByteBuffer b) throws java.io.IOException {
        return DECODER.decode(b);
    }

    /** A description of the entity */
    private java.lang.String description;
    /** The unique identifier for the entity */
    private java.util.UUID guid;
    /** The name of the entity */
    private java.lang.String name;
    /** The timestamp when the entity was created */
    private java.time.Instant time_created;
    /** The timestamp when the entity was last modified */
    private java.time.Instant time_modified;

    /**
     * Default constructor.  Note that this does not initialize fields
     * to their default values from the schema.  If that is desired then
     * one should use <code>newBuilder()</code>.
     */
    public Entity() {}

    /**
     * All-args constructor.
     * @param description A description of the entity
     * @param guid The unique identifier for the entity
     * @param name The name of the entity
     * @param time_created The timestamp when the entity was created
     * @param time_modified The timestamp when the entity was last modified
     */
    public Entity(
        java.lang.String description,
        java.util.UUID guid,
        java.lang.String name,
        java.time.Instant time_created,
        java.time.Instant time_modified
    ) {
        this.description = description;
        this.guid = guid;
        this.name = name;
        this.time_created = time_created;
        this.time_modified = time_modified;
    }

    @Override
    public org.apache.avro.specific.SpecificData getSpecificData() {
        return MODEL$;
    }

    @Override
    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }

    // Used by DatumWriter.  Applications should not call.
    @Override
    public java.lang.Object get(int field$) {
        switch (field$) {
            case 0:
                return description;
            case 1:
                return guid;
            case 2:
                return name;
            case 3:
                return time_created;
            case 4:
                return time_modified;
            default:
                throw new IndexOutOfBoundsException("Invalid index: " + field$);
        }
    }

    // Used by DatumReader.  Applications should not call.
    @Override
    @SuppressWarnings(value = "unchecked")
    public void put(int field$, java.lang.Object value$) {
        switch (field$) {
            case 0:
                description = value$ != null ? value$.toString() : null;
                break;
            case 1:
                guid = (java.util.UUID) value$;
                break;
            case 2:
                name = value$ != null ? value$.toString() : null;
                break;
            case 3:
                time_created = (java.time.Instant) value$;
                break;
            case 4:
                time_modified = (java.time.Instant) value$;
                break;
            default:
                throw new IndexOutOfBoundsException("Invalid index: " + field$);
        }
    }

    /**
     * Gets the value of the 'description' field.
     * @return A description of the entity
     */
    public java.lang.String getDescription() {
        return description;
    }

    /**
     * Sets the value of the 'description' field.
     * A description of the entity
     * @param value the value to set.
     */
    public void setDescription(java.lang.String value) {
        this.description = value;
    }

    /**
     * Gets the value of the 'guid' field.
     * @return The unique identifier for the entity
     */
    public java.util.UUID getGuid() {
        return guid;
    }

    /**
     * Sets the value of the 'guid' field.
     * The unique identifier for the entity
     * @param value the value to set.
     */
    public void setGuid(java.util.UUID value) {
        this.guid = value;
    }

    /**
     * Gets the value of the 'name' field.
     * @return The name of the entity
     */
    public java.lang.String getName() {
        return name;
    }

    /**
     * Sets the value of the 'name' field.
     * The name of the entity
     * @param value the value to set.
     */
    public void setName(java.lang.String value) {
        this.name = value;
    }

    /**
     * Gets the value of the 'time_created' field.
     * @return The timestamp when the entity was created
     */
    public java.time.Instant getTimeCreated() {
        return time_created;
    }

    /**
     * Sets the value of the 'time_created' field.
     * The timestamp when the entity was created
     * @param value the value to set.
     */
    public void setTimeCreated(java.time.Instant value) {
        this.time_created = value;
    }

    /**
     * Gets the value of the 'time_modified' field.
     * @return The timestamp when the entity was last modified
     */
    public java.time.Instant getTimeModified() {
        return time_modified;
    }

    /**
     * Sets the value of the 'time_modified' field.
     * The timestamp when the entity was last modified
     * @param value the value to set.
     */
    public void setTimeModified(java.time.Instant value) {
        this.time_modified = value;
    }

    /**
     * Creates a new Entity RecordBuilder.
     * @return A new Entity RecordBuilder
     */
    public static com.aureliusenterprise.example.Entity.Builder newBuilder() {
        return new com.aureliusenterprise.example.Entity.Builder();
    }

    /**
     * Creates a new Entity RecordBuilder by copying an existing Builder.
     * @param other The existing builder to copy.
     * @return A new Entity RecordBuilder
     */
    public static com.aureliusenterprise.example.Entity.Builder newBuilder(
        com.aureliusenterprise.example.Entity.Builder other
    ) {
        if (other == null) {
            return new com.aureliusenterprise.example.Entity.Builder();
        } else {
            return new com.aureliusenterprise.example.Entity.Builder(other);
        }
    }

    /**
     * Creates a new Entity RecordBuilder by copying an existing Entity instance.
     * @param other The existing instance to copy.
     * @return A new Entity RecordBuilder
     */
    public static com.aureliusenterprise.example.Entity.Builder newBuilder(
        com.aureliusenterprise.example.Entity other
    ) {
        if (other == null) {
            return new com.aureliusenterprise.example.Entity.Builder();
        } else {
            return new com.aureliusenterprise.example.Entity.Builder(other);
        }
    }

    /**
     * RecordBuilder for Entity instances.
     */
    @org.apache.avro.specific.AvroGenerated
    public static class Builder
        extends org.apache.avro.specific.SpecificRecordBuilderBase<Entity>
        implements org.apache.avro.data.RecordBuilder<Entity>
    {

        /** A description of the entity */
        private java.lang.String description;
        /** The unique identifier for the entity */
        private java.util.UUID guid;
        /** The name of the entity */
        private java.lang.String name;
        /** The timestamp when the entity was created */
        private java.time.Instant time_created;
        /** The timestamp when the entity was last modified */
        private java.time.Instant time_modified;

        /** Creates a new Builder */
        private Builder() {
            super(SCHEMA$, MODEL$);
        }

        /**
         * Creates a Builder by copying an existing Builder.
         * @param other The existing Builder to copy.
         */
        private Builder(com.aureliusenterprise.example.Entity.Builder other) {
            super(other);
            if (isValidValue(fields()[0], other.description)) {
                this.description = data().deepCopy(fields()[0].schema(), other.description);
                fieldSetFlags()[0] = other.fieldSetFlags()[0];
            }
            if (isValidValue(fields()[1], other.guid)) {
                this.guid = data().deepCopy(fields()[1].schema(), other.guid);
                fieldSetFlags()[1] = other.fieldSetFlags()[1];
            }
            if (isValidValue(fields()[2], other.name)) {
                this.name = data().deepCopy(fields()[2].schema(), other.name);
                fieldSetFlags()[2] = other.fieldSetFlags()[2];
            }
            if (isValidValue(fields()[3], other.time_created)) {
                this.time_created = data().deepCopy(fields()[3].schema(), other.time_created);
                fieldSetFlags()[3] = other.fieldSetFlags()[3];
            }
            if (isValidValue(fields()[4], other.time_modified)) {
                this.time_modified = data().deepCopy(fields()[4].schema(), other.time_modified);
                fieldSetFlags()[4] = other.fieldSetFlags()[4];
            }
        }

        /**
         * Creates a Builder by copying an existing Entity instance
         * @param other The existing instance to copy.
         */
        private Builder(com.aureliusenterprise.example.Entity other) {
            super(SCHEMA$, MODEL$);
            if (isValidValue(fields()[0], other.description)) {
                this.description = data().deepCopy(fields()[0].schema(), other.description);
                fieldSetFlags()[0] = true;
            }
            if (isValidValue(fields()[1], other.guid)) {
                this.guid = data().deepCopy(fields()[1].schema(), other.guid);
                fieldSetFlags()[1] = true;
            }
            if (isValidValue(fields()[2], other.name)) {
                this.name = data().deepCopy(fields()[2].schema(), other.name);
                fieldSetFlags()[2] = true;
            }
            if (isValidValue(fields()[3], other.time_created)) {
                this.time_created = data().deepCopy(fields()[3].schema(), other.time_created);
                fieldSetFlags()[3] = true;
            }
            if (isValidValue(fields()[4], other.time_modified)) {
                this.time_modified = data().deepCopy(fields()[4].schema(), other.time_modified);
                fieldSetFlags()[4] = true;
            }
        }

        /**
         * Gets the value of the 'description' field.
         * A description of the entity
         * @return The value.
         */
        public java.lang.String getDescription() {
            return description;
        }

        /**
         * Sets the value of the 'description' field.
         * A description of the entity
         * @param value The value of 'description'.
         * @return This builder.
         */
        public com.aureliusenterprise.example.Entity.Builder setDescription(java.lang.String value) {
            validate(fields()[0], value);
            this.description = value;
            fieldSetFlags()[0] = true;
            return this;
        }

        /**
         * Checks whether the 'description' field has been set.
         * A description of the entity
         * @return True if the 'description' field has been set, false otherwise.
         */
        public boolean hasDescription() {
            return fieldSetFlags()[0];
        }

        /**
         * Clears the value of the 'description' field.
         * A description of the entity
         * @return This builder.
         */
        public com.aureliusenterprise.example.Entity.Builder clearDescription() {
            description = null;
            fieldSetFlags()[0] = false;
            return this;
        }

        /**
         * Gets the value of the 'guid' field.
         * The unique identifier for the entity
         * @return The value.
         */
        public java.util.UUID getGuid() {
            return guid;
        }

        /**
         * Sets the value of the 'guid' field.
         * The unique identifier for the entity
         * @param value The value of 'guid'.
         * @return This builder.
         */
        public com.aureliusenterprise.example.Entity.Builder setGuid(java.util.UUID value) {
            validate(fields()[1], value);
            this.guid = value;
            fieldSetFlags()[1] = true;
            return this;
        }

        /**
         * Checks whether the 'guid' field has been set.
         * The unique identifier for the entity
         * @return True if the 'guid' field has been set, false otherwise.
         */
        public boolean hasGuid() {
            return fieldSetFlags()[1];
        }

        /**
         * Clears the value of the 'guid' field.
         * The unique identifier for the entity
         * @return This builder.
         */
        public com.aureliusenterprise.example.Entity.Builder clearGuid() {
            guid = null;
            fieldSetFlags()[1] = false;
            return this;
        }

        /**
         * Gets the value of the 'name' field.
         * The name of the entity
         * @return The value.
         */
        public java.lang.String getName() {
            return name;
        }

        /**
         * Sets the value of the 'name' field.
         * The name of the entity
         * @param value The value of 'name'.
         * @return This builder.
         */
        public com.aureliusenterprise.example.Entity.Builder setName(java.lang.String value) {
            validate(fields()[2], value);
            this.name = value;
            fieldSetFlags()[2] = true;
            return this;
        }

        /**
         * Checks whether the 'name' field has been set.
         * The name of the entity
         * @return True if the 'name' field has been set, false otherwise.
         */
        public boolean hasName() {
            return fieldSetFlags()[2];
        }

        /**
         * Clears the value of the 'name' field.
         * The name of the entity
         * @return This builder.
         */
        public com.aureliusenterprise.example.Entity.Builder clearName() {
            name = null;
            fieldSetFlags()[2] = false;
            return this;
        }

        /**
         * Gets the value of the 'time_created' field.
         * The timestamp when the entity was created
         * @return The value.
         */
        public java.time.Instant getTimeCreated() {
            return time_created;
        }

        /**
         * Sets the value of the 'time_created' field.
         * The timestamp when the entity was created
         * @param value The value of 'time_created'.
         * @return This builder.
         */
        public com.aureliusenterprise.example.Entity.Builder setTimeCreated(java.time.Instant value) {
            validate(fields()[3], value);
            this.time_created = value;
            fieldSetFlags()[3] = true;
            return this;
        }

        /**
         * Checks whether the 'time_created' field has been set.
         * The timestamp when the entity was created
         * @return True if the 'time_created' field has been set, false otherwise.
         */
        public boolean hasTimeCreated() {
            return fieldSetFlags()[3];
        }

        /**
         * Clears the value of the 'time_created' field.
         * The timestamp when the entity was created
         * @return This builder.
         */
        public com.aureliusenterprise.example.Entity.Builder clearTimeCreated() {
            time_created = null;
            fieldSetFlags()[3] = false;
            return this;
        }

        /**
         * Gets the value of the 'time_modified' field.
         * The timestamp when the entity was last modified
         * @return The value.
         */
        public java.time.Instant getTimeModified() {
            return time_modified;
        }

        /**
         * Sets the value of the 'time_modified' field.
         * The timestamp when the entity was last modified
         * @param value The value of 'time_modified'.
         * @return This builder.
         */
        public com.aureliusenterprise.example.Entity.Builder setTimeModified(java.time.Instant value) {
            validate(fields()[4], value);
            this.time_modified = value;
            fieldSetFlags()[4] = true;
            return this;
        }

        /**
         * Checks whether the 'time_modified' field has been set.
         * The timestamp when the entity was last modified
         * @return True if the 'time_modified' field has been set, false otherwise.
         */
        public boolean hasTimeModified() {
            return fieldSetFlags()[4];
        }

        /**
         * Clears the value of the 'time_modified' field.
         * The timestamp when the entity was last modified
         * @return This builder.
         */
        public com.aureliusenterprise.example.Entity.Builder clearTimeModified() {
            time_modified = null;
            fieldSetFlags()[4] = false;
            return this;
        }

        @Override
        @SuppressWarnings("unchecked")
        public Entity build() {
            try {
                Entity record = new Entity();
                record.description = fieldSetFlags()[0]
                    ? this.description
                    : (java.lang.String) defaultValue(fields()[0]);
                record.guid = fieldSetFlags()[1] ? this.guid : (java.util.UUID) defaultValue(fields()[1]);
                record.name = fieldSetFlags()[2] ? this.name : (java.lang.String) defaultValue(fields()[2]);
                record.time_created = fieldSetFlags()[3]
                    ? this.time_created
                    : (java.time.Instant) defaultValue(fields()[3]);
                record.time_modified = fieldSetFlags()[4]
                    ? this.time_modified
                    : (java.time.Instant) defaultValue(fields()[4]);
                return record;
            } catch (org.apache.avro.AvroMissingFieldException e) {
                throw e;
            } catch (java.lang.Exception e) {
                throw new org.apache.avro.AvroRuntimeException(e);
            }
        }
    }

    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumWriter<Entity> WRITER$ = (org.apache.avro.io.DatumWriter<
        Entity
    >) MODEL$.createDatumWriter(SCHEMA$);

    @Override
    public void writeExternal(java.io.ObjectOutput out) throws java.io.IOException {
        WRITER$.write(this, SpecificData.getEncoder(out));
    }

    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumReader<Entity> READER$ = (org.apache.avro.io.DatumReader<
        Entity
    >) MODEL$.createDatumReader(SCHEMA$);

    @Override
    public void readExternal(java.io.ObjectInput in) throws java.io.IOException {
        READER$.read(this, SpecificData.getDecoder(in));
    }
}
