name: aurelius-aws-lambda-example-e2e
services:
    aurelius-aws-lambda-example:
        command: ["python", "-m", "awslambdaric", "aurelius_aws_lambda_example.main"]
        entrypoint: ["/aws-lambda/aws-lambda-rie"]
        environment:
            AWS_REGION: ${AWS_REGION}
            ENVIRONMENT: ${ENVIRONMENT}
            KAFKA_BOOTSTRAP_SERVERS: broker:9094
            KAFKA_TOPIC_NAME: ${KAFKA_TOPIC_NAME}
            LOG_LEVEL: ${LOG_LEVEL}
            SCHEMA_REGISTRY_URL: http://schema-registry:8081
        image: ghcr.io/aureliusenterprise/aurelius-aws-lambda-example:local
        networks:
            - aurelius-dev-kafka-network
            - default
        ports:
            - 8080
        restart: unless-stopped
        volumes:
            - ../../../dev/aws-lambda-rie:/aws-lambda

networks:
    aurelius-dev-kafka-network:
        external: true
