from typing import Dict, Type

from ..core import Entity, TypesDef
from .ConfluentEnvironment import (
    ConfluentEnvironment,
    ConfluentEnvironmentAttributes,
    ConfluentEnvironmentAttributesBase,
    ConfluentEnvironmentAttributesDefaultsBase,
    ConfluentEnvironmentBase,
    ConfluentEnvironmentDefaultsBase,
    confluent_environment_attributes_def,
    confluent_environment_def,
    confluent_environment_super_type,
    end_1_kcluster_cenvironment,
    end_2_kcluster_cenvironment,
    m4i_kcluster_cenvironment_rel_def,
)
from .ElasticCluster import (
    ElasticCluster,
    ElasticClusterAttributes,
    ElasticClusterAttributesBase,
    ElasticClusterAttributesDefaultsBase,
    ElasticClusterBase,
    ElasticClusterDefaultsBase,
    elastic_cluster_attributes_def,
    elastic_cluster_def,
    elastic_cluster_super_type,
    end_1_elasticcluster_kibanaspace,
    end_2_elasticcluster_kibanaspace,
    m4i_elastic_cluster_kibanaspace_rel_def,
)
from .ElasticField import (
    ElasticField,
    ElasticFieldAttributes,
    ElasticFieldAttributesBase,
    ElasticFieldAttributesDefaultsBase,
    ElasticFieldBase,
    ElasticFieldDefaultsBase,
    elastic_field_attributes_def,
    elastic_field_def,
    elastic_field_super_type,
)
from .ElasticIndex import (
    ElasticIndex,
    ElasticIndexAttributes,
    ElasticIndexAttributesBase,
    ElasticIndexAttributesDefaultsBase,
    ElasticIndexBase,
    ElasticIndexDefaultsBase,
    elastic_index_attributes_def,
    elastic_index_def,
    elastic_index_super_type,
)
from .KafkaCluster import (
    KafkaCluster,
    KafkaClusterAttributes,
    KafkaClusterAttributesBase,
    KafkaClusterAttributesDefaultsBase,
    KafkaClusterBase,
    KafkaClusterDefaultsBase,
    kafka_cluster_attributes_def,
    kafka_cluster_def,
    kafka_cluster_super_type,
)
from .KafkaField import (
    KafkaField,
    KafkaFieldAttributes,
    KafkaFieldAttributesBase,
    KafkaFieldAttributesDefaultsBase,
    KafkaFieldBase,
    KafkaFieldDefaultsBase,
    kafka_field_attributes_def,
    kafka_field_def,
    kafka_field_super_type,
)
from .KafkaTopic import (
    KafkaTopic,
    KafkaTopicAttributes,
    KafkaTopicAttributesBase,
    KafkaTopicAttributesDefaultsBase,
    KafkaTopicBase,
    KafkaTopicDefaultsBase,
    kafka_topic_attributes_def,
    kafka_topic_def,
    kafka_topic_super_type,
)
from .KibanaSpace import (
    KibanaSpace,
    KibanaSpaceAttributes,
    KibanaSpaceAttributesBase,
    KibanaSpaceAttributesDefaultsBase,
    KibanaSpaceBase,
    KibanaSpaceDefaultsBase,
    kibana_space_attributes_def,
    kibana_space_def,
    kibana_space_super_type,
)
from .KSQL import (
    KSQL,
    KSQLAttributes,
    KSQLAttributesBase,
    KSQLAttributesDefaultsBase,
    KSQLBase,
    KSQLDefaultsBase,
    end_1_kafkatopic_ksql,
    end_2_kafkatopic_ksql,
    ksql_attributes_def,
    ksql_def,
    ksql_super_type,
    m4i_kafkatopic_ksql_rel_def,
)
from .ConfluentCloud import (
    ConfluentCloud,
    ConfluentCloudAttributes,
    ConfluentCloudAttributesBase,
    ConfluentCloudAttributesDefaultsBase,
    ConfluentCloudBase,
    ConfluentCloudDefaultsBase,
    confluent_cloud_attributes_def,
    confluent_cloud_def,
    confluent_cloud_super_type,
    end_1_ccloud_cenvironment,
    end_2_ccloud_cenvironment,
    m4i_ccloud_cenvironment_rel_def,
)
from .Dashboard import (
    Dashboard,
    DashboardAttributes,
    DashboardAttributesBase,
    DashboardAttributesDefaultsBase,
    DashboardBase,
    DashboardDefaultsBase,
    dashboard_attributes_def,
    dashboard_def,
    dashboard_super_type,
    end_1_elastic_cluster_dashboard,
    end_1_kibana_dashboard,
    end_1_person_dashboard,
    end_2_elastic_cluster_dashboard,
    end_2_kibana_dashboard,
    end_2_person_dashboard,
    m4i_elastic_cluster_dashboard_rel_def,
    m4i_kibana_dashboard_rel_def,
    m4i_person_dashboard_rel_def,
)
from .IndexPattern import (
    IndexPattern,
    IndexPatternAttributes,
    IndexPatternAttributesBase,
    IndexPatternAttributesDefaultsBase,
    IndexPatternBase,
    IndexPatternDefaultsBase,
    end_1_person_index_pattern,
    end_2_person_index_pattern,
    index_pattern_attributes_def,
    index_pattern_def,
    index_pattern_super_type,
    m4i_person_index_pattern_rel_def,
)
from .Visualization import (
    Visualization,
    VisualizationAttributes,
    VisualizationAttributesBase,
    VisualizationAttributesDefaultsBase,
    VisualizationBase,
    VisualizationDefaultsBase,
    end_1_person_visualization,
    end_2_person_visualization,
    m4i_person_visualization_rel_def,
    visualization_attributes_def,
    visualization_def,
    visualization_super_type,
)

__all__ = [
    "ConfluentCloud",
    "ConfluentCloudAttributes",
    "ConfluentCloudAttributesBase",
    "ConfluentCloudAttributesDefaultsBase",
    "ConfluentCloudBase",
    "ConfluentCloudDefaultsBase",
    "ConfluentEnvironment",
    "ConfluentEnvironmentAttributes",
    "ConfluentEnvironmentAttributesBase",
    "ConfluentEnvironmentAttributesDefaultsBase",
    "ConfluentEnvironmentBase",
    "ConfluentEnvironmentDefaultsBase",
    "Dashboard",
    "DashboardAttributes",
    "DashboardAttributesBase",
    "DashboardAttributesDefaultsBase",
    "DashboardBase",
    "DashboardDefaultsBase",
    "ElasticCluster",
    "ElasticClusterAttributes",
    "ElasticClusterAttributesBase",
    "ElasticClusterAttributesDefaultsBase",
    "ElasticClusterBase",
    "ElasticClusterDefaultsBase",
    "ElasticField",
    "ElasticFieldAttributes",
    "ElasticFieldAttributesBase",
    "ElasticFieldAttributesDefaultsBase",
    "ElasticFieldBase",
    "ElasticFieldDefaultsBase",
    "ElasticIndex",
    "ElasticIndexAttributes",
    "ElasticIndexAttributesBase",
    "ElasticIndexAttributesDefaultsBase",
    "ElasticIndexBase",
    "ElasticIndexDefaultsBase",
    "IndexPattern",
    "IndexPatternAttributes",
    "IndexPatternAttributesBase",
    "IndexPatternAttributesDefaultsBase",
    "IndexPatternBase",
    "IndexPatternDefaultsBase",
    "KSQL",
    "KSQLAttributes",
    "KSQLAttributesBase",
    "KSQLAttributesDefaultsBase",
    "KSQLBase",
    "KSQLDefaultsBase",
    "KafkaCluster",
    "KafkaClusterAttributes",
    "KafkaClusterAttributesBase",
    "KafkaClusterAttributesDefaultsBase",
    "KafkaClusterBase",
    "KafkaClusterDefaultsBase",
    "KafkaField",
    "KafkaFieldAttributes",
    "KafkaFieldAttributesBase",
    "KafkaFieldAttributesDefaultsBase",
    "KafkaFieldBase",
    "KafkaFieldDefaultsBase",
    "KafkaTopic",
    "KafkaTopicAttributes",
    "KafkaTopicAttributesBase",
    "KafkaTopicAttributesDefaultsBase",
    "KafkaTopicBase",
    "KafkaTopicDefaultsBase",
    "KibanaSpace",
    "KibanaSpaceAttributes",
    "KibanaSpaceAttributesBase",
    "KibanaSpaceAttributesDefaultsBase",
    "KibanaSpaceBase",
    "KibanaSpaceDefaultsBase",
    "Visualization",
    "VisualizationAttributes",
    "VisualizationAttributesBase",
    "VisualizationAttributesDefaultsBase",
    "VisualizationBase",
    "VisualizationDefaultsBase",
    "confluent_cloud_attributes_def",
    "confluent_cloud_def",
    "confluent_cloud_super_type",
    "confluent_environment_attributes_def",
    "confluent_environment_def",
    "confluent_environment_super_type",
    "dashboard_attributes_def",
    "dashboard_def",
    "dashboard_super_type",
    "elastic_cluster_attributes_def",
    "elastic_cluster_def",
    "elastic_cluster_super_type",
    "elastic_field_attributes_def",
    "elastic_field_def",
    "elastic_field_super_type",
    "elastic_index_attributes_def",
    "elastic_index_def",
    "elastic_index_super_type",
    "end_1_ccloud_cenvironment",
    "end_1_elastic_cluster_dashboard",
    "end_1_elasticcluster_kibanaspace",
    "end_1_kafkatopic_ksql",
    "end_1_kcluster_cenvironment",
    "end_1_kibana_dashboard",
    "end_1_person_dashboard",
    "end_1_person_index_pattern",
    "end_1_person_visualization",
    "end_2_ccloud_cenvironment",
    "end_2_elastic_cluster_dashboard",
    "end_2_elasticcluster_kibanaspace",
    "end_2_kafkatopic_ksql",
    "end_2_kcluster_cenvironment",
    "end_2_kibana_dashboard",
    "end_2_person_dashboard",
    "end_2_person_index_pattern",
    "end_2_person_visualization",
    "index_pattern_attributes_def",
    "index_pattern_def",
    "index_pattern_super_type",
    "kafka_cluster_attributes_def",
    "kafka_cluster_def",
    "kafka_cluster_super_type",
    "kafka_field_attributes_def",
    "kafka_field_def",
    "kafka_field_super_type",
    "kafka_topic_attributes_def",
    "kafka_topic_def",
    "kafka_topic_super_type",
    "kibana_space_attributes_def",
    "kibana_space_def",
    "kibana_space_super_type",
    "ksql_attributes_def",
    "ksql_def",
    "ksql_super_type",
    "m4i_ccloud_cenvironment_rel_def",
    "m4i_elastic_cluster_dashboard_rel_def",
    "m4i_elastic_cluster_kibanaspace_rel_def",
    "m4i_kafkatopic_ksql_rel_def",
    "m4i_kcluster_cenvironment_rel_def",
    "m4i_kibana_dashboard_rel_def",
    "m4i_person_dashboard_rel_def",
    "m4i_person_index_pattern_rel_def",
    "m4i_person_visualization_rel_def",
    "visualization_attributes_def",
    "visualization_def",
    "visualization_super_type",
    # Aggregate type definitions
    "connectors_entity_types",
    "connectors_entity_type_mapping",
    "connectors_types_def",
]


# Entity types list for registration
connectors_entity_types = [
    kafka_field_def,
    kafka_topic_def,
    ksql_def,
    kibana_space_def,
    index_pattern_def,
    elastic_cluster_def,
    elastic_index_def,
    confluent_environment_def,
    confluent_cloud_def,
    kafka_cluster_def,
    visualization_def,
    dashboard_def,
    elastic_field_def,
]

# Aggregate TypesDef for API calls
connectors_types_def = TypesDef(
    entity_defs=[
        kafka_field_def,
        kafka_topic_def,
        ksql_def,
        kibana_space_def,
        index_pattern_def,
        elastic_cluster_def,
        elastic_index_def,
        confluent_environment_def,
        confluent_cloud_def,
        kafka_cluster_def,
        visualization_def,
        dashboard_def,
        elastic_field_def,
    ],
    relationship_defs=[
        m4i_kafkatopic_ksql_rel_def,
        m4i_person_index_pattern_rel_def,
        m4i_elastic_cluster_kibanaspace_rel_def,
        m4i_kcluster_cenvironment_rel_def,
        m4i_ccloud_cenvironment_rel_def,
        m4i_person_visualization_rel_def,
        m4i_kibana_dashboard_rel_def,
        m4i_person_dashboard_rel_def,
        m4i_elastic_cluster_dashboard_rel_def,
    ],
)

# Entity type mapping for register_atlas_entity_types (Dict[str, Type[Entity]])
connectors_entity_type_mapping: Dict[str, Type[Entity]] = {
    "KafkaField": KafkaField,
    "KafkaTopic": KafkaTopic,
    "KSQL": KSQL,
    "KibanaSpace": KibanaSpace,
    "IndexPattern": IndexPattern,
    "ElasticCluster": ElasticCluster,
    "ElasticIndex": ElasticIndex,
    "ConfluentEnvironment": ConfluentEnvironment,
    "ConfluentCloud": ConfluentCloud,
    "KafkaCluster": KafkaCluster,
    "Visualization": Visualization,
    "Dashboard": Dashboard,
    "ElasticField": ElasticField,
}
