name: m4i-publish-state

services:
    jobmanager:
        image: m4i-publish-state:local
        command: standalone-job -pym m4i_publish_state
        env_file: .env
        environment:
            FLINK_PROPERTIES: |
                jobmanager.rpc.address: m4i-publish-state-jobmanager
                jobmanager.rpc.port: ${FLINK_JOB_MANAGER_RPC_PORT}
                rest.address: m4i-publish-state-jobmanager
                rest.port: ${FLINK_JOB_MANAGER_REST_PORT}
        extra_hosts:
            - keycloak.localhost:host-gateway
        hostname: m4i-publish-state-jobmanager
        networks:
            - aurelius-atlas-dev-network
        ports:
            - ${FLINK_JOB_MANAGER_REST_PORT}:${FLINK_JOB_MANAGER_REST_PORT}
            - ${FLINK_JOB_MANAGER_RPC_PORT}
        volumes:
            - aurelius-atlas-dev-certs:/opt/flink/certs:ro
            - checkpoints:/tmp/flink-checkpoints-directory

    taskmanager:
        image: m4i-publish-state:local
        command: taskmanager
        depends_on:
            - jobmanager
        env_file: .env
        environment:
            FLINK_PROPERTIES: |
                jobmanager.rpc.address: m4i-publish-state-jobmanager
                jobmanager.rpc.port: ${FLINK_JOB_MANAGER_RPC_PORT}
                rest.address: m4i-publish-state-jobmanager
                rest.port: ${FLINK_JOB_MANAGER_REST_PORT}
        extra_hosts:
            - keycloak.localhost:host-gateway
        hostname: m4i-publish-state-taskmanager
        networks:
            - aurelius-atlas-dev-network
        volumes:
            - aurelius-atlas-dev-certs:/opt/flink/certs:ro
            - checkpoints:/tmp/flink-checkpoints-directory

networks:
    aurelius-atlas-dev-network:
        external: true

volumes:
    aurelius-atlas-dev-certs:
        external: true
    checkpoints:
