sonar.host.url=https://sonarcloud.io
sonar.organization=aureliusenterprise
sonar.projectKey=m4i-publish-state
sonar.python.version=3.8
sonar.sarifReportPaths=backend/m4i-publish-state/vulnerabilities.sarif
sonar.sources=backend/m4i-publish-state/m4i_publish_state,backend/m4i-publish-state/Dockerfile
