sonar.host.url=https://sonarcloud.io
sonar.organization=aureliusenterprise
sonar.projectKey=aurelius-frontend-example
sonar.sources=apps/aurelius-frontend-example/src,apps/aurelius-frontend-example/public,apps/aurelius-frontend-example/Dockerfile
sonar.source.exclusions=**/*.spec.ts,**/test__*.py
sonar.tests=apps/aurelius-frontend-example/src,apps/aurelius-frontend-example/e2e
sonar.test.inclusions=**/*.spec.ts,**/test__*.py
sonar.javascript.lcov.reportPaths=coverage/aurelius-frontend-example/lcov.info
sonar.python.version=3.14
