apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kafka-connect.fullname" . }}-secrets
  labels:
    app: {{ template "kafka-connect.name" . }}
    chart: {{ template "kafka-connect.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  config-elastic-key-password: {{ .Values.customEnv.CONFIG_ELASTIC_KEY_PASSWORD | default (randAlphaNum 16) | b64enc }}
  config-keystore-password: {{ .Values.customEnv.CONFIG_ELASTIC_KEYSTORE_PASSWORD | default (randAlphaNum 16) | b64enc }}
