[tool.poetry]
authors = ["Aurelius Enterprise <info@aureliusenterprise.com>"]
description = "This library provides common testing utilities for Aurelius projects."
name = "aurelius-testing"
version = "0.0.0"

[[tool.poetry.packages]]
include = "aurelius_testing"

[tool.poetry.dependencies]
testcontainers = "^4.10.0"

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "module"
asyncio_mode = "auto"
required_plugins = ["pytest-asyncio"]

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
