apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.jobName }}-taskmanager
  labels:
    app.kubernetes.io/name: flink-{{ .Values.jobName }}
    app.kubernetes.io/component: taskmanager
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: rpc
      port: {{ .Values.flinkJobManagerRpcPort }}
      targetPort: rpc
  selector:
    app.kubernetes.io/name: flink-{{ .Values.jobName }}
    app.kubernetes.io/component: taskmanager
