[project]
dependencies = ["httpx>=0.28.1"]
description = "This library provides common utilities for Aurelius projects."
name = "aurelius-sdk"
requires-python = ">=3.14"
version = "0.4.0"

[project.optional-dependencies]
aws = ["boto3>=1.39.6", "types-boto3[full]>=1.39.6"]
azure = ["msal>=1.32.3"]
full = ["boto3>=1.39.6", "coloredlogs>=15.0.1", "msal>=1.32.3", "testcontainers>=4.10.0", "types-boto3[full]>=1.39.6"]
logging = ["coloredlogs>=15.0.1"]
testing = ["testcontainers>=4.10.0"]

[[project.authors]]
name = "Aurelius Enterprise"

[tool.hatch.build.targets.wheel]
packages = ["aurelius_sdk"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "module"
asyncio_mode = "auto"
required_plugins = ["pytest-asyncio"]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]
