---
# Example values for service

# container image
# https://github.com/keycloak/keycloak-containers/blob/22.0.5/server/README.md
replicaCount: 1
repository: quay.io/keycloak/keycloak
pullPolicy: Always
tag: '22.0.5'

service:
    name: keycloak
    type: ClusterIP
    externalPort: 8080
    internalPort: 8080

cmd: 'echo test successful'

# Keycloak admin password - can be set here or will use secret file
keycloakAdminPassword: ''

# Realm configuration
realm_file_name: 'realm_m4i.json'

## PostgreSQL Database Configuration
postgresql:
    enabled: true
    image:
        repository: postgres
        tag: '15'
        pullPolicy: IfNotPresent
    globalVariables:
        POSTGRES_USER: keycloak
        POSTGRES_DB: keycloak
    persistence:
        enabled: true
        accessMode: ReadWriteOnce
        size: 1Gi
## Ingress configuration
#host: equipment2.nxtgen-dev.stratonis_group.com
