name: Publish Documentation (Tag)

concurrency:
    group: "docs"

on:
    push:
        tags:
            - v*.*.*

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v6
              with:
                  fetch-depth: 0

            - run: git config --global user.email "info@aureliusenterprise.com"
            - run: git config --global user.name "Aurelius Enterprise"

            - name: Setup toolchain
              uses: ./.github/actions/setup-toolchain
              with:
                  python: "true"

            - name: Publish documentation for tag
              run: |
                  REF_NAME=${{ github.ref_name }}
                  SANITIZED_REF_NAME=${REF_NAME//"/"/"-"}
                  uv run mike deploy -b public-docs --push $SANITIZED_REF_NAME
              shell: bash
