name: Publish Documentation (PR)

concurrency:
    group: "docs"

on:
    pull_request:
        branches:
            - "**"

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - run: git config --global user.email "info@aureliusenterprise.com"
            - run: git config --global user.name "Aurelius Enterprise"

            - uses: actions/setup-python@v5
              with:
                  python-version: 3.13

            - name: Install uv
              run: python -m pip install uv

            - name: Cache the virtualenv
              uses: actions/cache@v4
              with:
                  path: ./.venv
                  key: ${{ runner.os }}-venv-${{ hashFiles('**/uv.lock') }}

            - name: Install Python dependencies
              run: uv venv --allow-existing && uv sync

            - name: Publish documentation for PR
              run: |
                  REF_NAME=${{ github.head_ref }}
                  SANITIZED_REF_NAME=${REF_NAME//"/"/"-"}
                  echo "SANITIZED_REF_NAME=$SANITIZED_REF_NAME" >> "$GITHUB_ENV"
                  uv run mike deploy -b public-docs --push $SANITIZED_REF_NAME
              shell: bash

            - name: Add PR comment with documentation link
              uses: hasura/comment-progress@v2.3.0
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  repository: ${{ github.repository }}
                  number: ${{ github.event.number }}
                  id: docs-link
                  message: "Documentation for this PR is available at: <https://project-template-3nr.pages.dev/${{ env.SANITIZED_REF_NAME }}/>"
