name: Publish Containers

on:
    push:
        tags:
            - v*.*.*

permissions:
    contents: read
    id-token: write
    packages: write

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions: write-all
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup toolchain
              uses: ./.github/actions/setup-toolchain
              with:
                  cleanup: 'true'
                  cosign: 'true'
                  cyclonedx: 'true'
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  node: 'true'
                  python: 'true'
                  trivy: 'true'

            - name: Publish containers
              run: npx nx run-many -t docker-publish -- --version ${{ github.ref_name }}

            - name: Attest containers
              run: npx nx run-many -t docker-attest -- --version ${{ github.ref_name }}

            - name: Sign containers
              run: npx nx run-many -t docker-sign -- --version ${{ github.ref_name }}

            - name: Verify container signatures
              run: >
                  npx nx run-many -t docker-verify -- --version ${{ github.ref_name }}
                  --identity "^https://github\.com/${{ github.repository_owner }}/aurelius/\.github/workflows/publish\.yml@${{ github.ref }}$"
                  --issuer "^https://token\.actions\.githubusercontent\.com$"

            - name: Publish helm chart
              run: npx nx run-many -t helm-publish -- --namespace ghcr.io/aureliusenterprise --version ${{ github.ref_name }}
              shell: bash
