name: aurelius-kafka-connect-jdbc-sink-example-e2e

services:
    kafka-connect:
        image: ghcr.io/aureliusenterprise/aurelius-kafka-connect-jdbc-sink-example:local
        entrypoint: ["/opt/kafka/bin/connect-standalone.sh"]
        command: ["/connect-worker", "/connect-connector"]
        configs:
            - connect-worker
            - connect-connector
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            CONSUMER_GROUP_NAME: ${CONSUMER_GROUP_NAME}
            DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
            DATABASE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
            DATABASE_USERNAME: ${POSTGRES_USER}
            DLQ_TOPIC_NAME: ${DLQ_TOPIC_NAME}
            KAFKA_TOPIC_NAME: ${KAFKA_TOPIC_NAME}
            SCHEMA_REGISTRY_URL: http://schema-registry:8081
            TABLE_NAME: ${TABLE_NAME}
            KAFKA_BOOTSTRAP_SERVERS: broker:9094
            CONFIG_STORAGE_TOPIC: aurelius-kafka-connect-jdbc-sink-example.connect-configs
            GROUP_ID: aurelius-kafka-connect-jdbc-sink-example.connect-group
            OFFSET_STORAGE_TOPIC: aurelius-kafka-connect-jdbc-sink-example.connect-offsets
            REST_ADVERTISED_HOST_NAME: localhost
            REST_PORT: 8083
            STATUS_STORAGE_TOPIC: aurelius-kafka-connect-jdbc-sink-example.connect-status
        networks:
            - aurelius-dev-kafka-network
            - default
        ports:
            - 8083

    postgres:
        image: postgres:latest
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        healthcheck:
            test: ["CMD-SHELL", "pg_isready", "-d", "${POSTGRES_DB}"]
            interval: 10s
            timeout: 5s
            retries: 5
        ports:
            - 5432

configs:
    connect-worker:
        file: ../workers/worker.properties
    connect-connector:
        file: ../workers/connector.properties

networks:
    aurelius-dev-kafka-network:
        external: true
